main: games.indigo.adventcalendar.Main
name: AdventCalendar
version: 2.0
author: TheBirmanator
description: Advent Calendar 2019
api-version: 1.14
commands:
  adventcalendar:
    usage: /<command>
    aliases: [ advent, adv, adventc ]
    description: Opens the advent calendar